### ISSUE TITLE
foundation data() function broken with npm-scss 3.4.0-beta

### ISSUE THREAD

**Issue by aheissenberger** [juliancwirko/meteor-zf5#10]
details here:
https://github.com/fourseven/meteor-scss/issues/152

temporare solution:
```bash
meteor remove juliancwirko:zf5
mkdir packages
cd packages
git clone https://github.com/fourseven/meteor-scss.git
```
=> change in `/packages/meteor-scss/package.js` 'node-sass': '3.4.0-beta1' => 'node-sass': '3.4.1'
```bash
cd ..
meteor add fourseven:scss
meteor add juliancwirko:zf5@2.0.1
```

**Comment by juliancwirko** [comment]
Hey, you are absolutely right. There was a regression in 3.4.0: https://github.com/sass/libsass/issues/1624 ...all we need here is `fourseven:scss` package update

**Comment by juliancwirko** [comment]
Ok, so it should be ok now. There is `juliancwirko:zf5@2.0.2` with `fourseven:scss@3.4.1`

**Comment by aheissenberger** [comment]
Thanks for the quick update @juliancwirko @fourseven
