### ISSUE TITLE
Media query expression must begin with '(' 

### ISSUE THREAD

**Issue by chackerian** [juliancwirko/meteor-zf5#12]
When I try uncommenting `@import "settings"` from my main.scss file I get this error:

>  While processing files with fourseven:scss (for target web.browser):
> /client/stylesheets/main.scss: Scss compiler error: media query expression must begin with '('

I properly got the contents of this file from scss/foundation/_settings.scss and replaced the functions 'foundation/functions' import path

The error goes away when I recomment the `@import "settings"` line

**Comment by chackerian** [comment]
I discovered what it was. `@import "settings"`was lacking a comment on the end. You might want to add that to the project (even though it was my fault for not noticing).

**Comment by juliancwirko** [comment]
Hi, thanks. Added.

**Comment by chackerian** [comment]
By the way, do you know if ALL the Foundation 5 JS should work with this package? 

I was trying to use [Top Bar](http://foundation.zurb.com/sites/docs/v/5.5.3/components/topbar.html) and it was displaying properly but when I viewed it on my phone, the mobile ☰ menu wasn't displaying. I used demo code so I don't think I made any mistake.

**Comment by juliancwirko** [comment]
Hard to say, maybe try new Foundation 6 from Npm. You can use it that way with new Meteor from version 1.3. Here is the example: https://github.com/juliancwirko/meteor-npm-foundation-test
