### ISSUE TITLE
JavaScript not Initializing

### ISSUE THREAD

**Issue by merlinpatt** [juliancwirko/meteor-zf5#4]
I have attempted to use the template rendered reflow method and the Iron Router method to init Foundation. I have also attempted to use both at once. None of these options are working.

I am attempting to run this on body (`Template.body.rendered`) because I am using their off canvas menu.

**Comment by juliancwirko** [comment]
You should place offcanvas in some wrapper and then init foundation offcanvas when this wrapper is rendered. `Template.mainWrapperWithOffcanvas.onRendered(function () {...})` 

There isn't something like 'body rendered' in Meteor. You could try with `Meteor.startup(function () {...})` but it is better to use a wrapper.

I don't remember exactly how offcanvas should work, but you can probably create a template with an offcanvas html and then init it on rendered callback.

Bassicaly you need to have all of your offcanvas html in the DOM before you init Foundation.
