### ISSUE TITLE
Path to 'foundation/functions' incorrect

### ISSUE THREAD

**Issue by DevTash** [juliancwirko/meteor-zf5#6]
Meteor, more specifically fourseven:scss, couldn't import the '_functions' partial located in 'scss/foundation' because of the new path system in the fourseven:scss package.
![error](https://cloud.githubusercontent.com/assets/14331649/10270850/e3b8b8bc-6af6-11e5-961c-dbc9f8ddc2a3.png)

Line 58 in '_settings' partial was: @import '/foundation/functions'; 
![before](https://cloud.githubusercontent.com/assets/14331649/10270852/ebc35e18-6af6-11e5-93eb-6bb090399f67.png)

Changing it to: @import '{juliancwirko:zf5}/scss/foundation/functions'; - fixed the import issue at build time.
![after](https://cloud.githubusercontent.com/assets/14331649/10270853/f7fa1fbe-6af6-11e5-8fdd-673fc291d792.png)

**Comment by juliancwirko** [comment]
are you using version 2.0.0 ? It should work with new version.

**Comment by juliancwirko** [comment]
I have edited documentation info.

**Comment by DevTash** [comment]
You are correct, I am using version 2.0.0 and have the _settings file in my app.
Glad to have helped.

**Comment by juliancwirko** [comment]
Yes, thanks for that tip :)
