### ISSUE TITLE
anchors used for accordion are broken with last Iron Router version

### ISSUE THREAD

**Issue by sveinburne** [juliancwirko/meteor-zf5#8]
Reason : A `<a href="#tasks">click-me</a>` anchor will now route to `website/#!tasks` instead of `website/#!currentpath/#tasks`

The workaround I found is to disable shebang prefixes `#!` used apprently for compatibility with IE7 and 8
    
    Iron.Location.configure({useHashPaths:false})

which is a fixaround I wanted to share. 

Issue referenced on `iron-router` : iron-meteor/iron-router#1457

**Comment by juliancwirko** [comment]
Cool! I will place it in the readme. Thank you!
