### ISSUE TITLE
File to import: {juliancwirko:zf5}/scss/foundation/components/grid.scss not found.

### ISSUE THREAD

**Issue by dyscalcolon** [juliancwirko/meteor-zf5#9]
I want to import the f5 files as prescribed by the readme file. My import code:

    @charset "UTF-8";
    
    //@import "{juliancwirko:zf5}/scss/normalize.scss";;
    
    //local Foundation settings file. Copy it from git repo -> scss/foundation/_settings.scss near main .scss         file. Then Uncomment the line below.
    @import '{}/client/f5settings.import.scss';
    
    //local Foundation settings file. You can overwrite the settings here. Copy it from git repo ->     scss/foundation/_settings.scss near main .scss file. Replace the functions path with     '{juliancwirko:zf5}/scss/foundation/functions' Then Uncomment the line below:
    // @import "settings"
    
    @import "{juliancwirko:zf5}/scss/foundation/components/grid.scss";
    ...
The error it throws:
> Errors prevented startup:
> 
> While processing files with fourseven:scss (for target web.browser):
> /client/foundation.scss: Scss compiler error: File to import: > {juliancwirko:zf5}/scss/foundation/components/grid.scss not found. Import origin: > /client/foundation.scss
> 
> 
> Your application has errors. Waiting for file change.

Using meteor 1.2.0.2 and fourseven:scss 3.3.3_3 and zf5 1.0.4

What is wrong here?

**Comment by dyscalcolon** [comment]
https://github.com/juliancwirko/meteor-zf5/issues/7 helped me to solve the problem.

    meteor remove juliancwirko:zf5
    meteor remove fourseven:scss
    meteor add juliancwirko:zf5@2.0.0

Got the job done, now that zf5 is running on 2.0.0!

**Comment by juliancwirko** [comment]
Yes, Meteor has w weird dependency system ;) It won't update it automatically (maybe it is good behaviour ;) )

I will place this information in the readme. Thanks.
